sudo: false
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
script:
- npm run build && npm test
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
install:
- npm install
